FROM ubuntu:16.04

ENV BUILD_PACKAGES bash ruby-dev libgl1-mesa-glx

ENV RUBY_PACKAGES ruby ruby-bundler

RUN apt-get update && \
    apt-get install -y curl build-essential libpng12-dev libffi-dev  && \
    apt-get install -y $BUILD_PACKAGES && \
    apt-get install -y --no-install-recommends $RUBY_PACKAGES && \
    apt-get clean && \

    # clean up
    rm -rf /var/lib/apt/lists/* && \
    truncate -s 0 /var/log/*log && \

    # Setup Rubygems
    echo 'gem: --no-document' > /etc/gemrc && \
    gem install bundler && gem update --system

RUN curl -sSL -o installer.sh https://repo.continuum.io/archive/Anaconda3-5.0.0-Linux-x86_64.sh && \
    bash /installer.sh -b -f && \
    rm /installer.sh

ENV PATH "$PATH:/root/anaconda3/bin"

RUN mkdir /usr/app

COPY Gemfile /usr/app/
COPY Gemfile.lock /usr/app/

COPY . /usr/app

WORKDIR /usr/app

RUN bundle config --global silence_root_warning 1
RUN bundle install --system

CMD ["ruby"]
